// Generated by view binder compiler. Do not edit!
package com.example.quiz.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.quiz.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final EditText age1;

  @NonNull
  public final EditText email1;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final EditText name1;

  @NonNull
  public final EditText pass1;

  @NonNull
  public final Button signup;

  @NonNull
  public final TextView textView4;

  @NonNull
  public final TextView textView5;

  private ActivityMainBinding(@NonNull ConstraintLayout rootView, @NonNull EditText age1,
      @NonNull EditText email1, @NonNull ImageView imageView2, @NonNull EditText name1,
      @NonNull EditText pass1, @NonNull Button signup, @NonNull TextView textView4,
      @NonNull TextView textView5) {
    this.rootView = rootView;
    this.age1 = age1;
    this.email1 = email1;
    this.imageView2 = imageView2;
    this.name1 = name1;
    this.pass1 = pass1;
    this.signup = signup;
    this.textView4 = textView4;
    this.textView5 = textView5;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.age1;
      EditText age1 = ViewBindings.findChildViewById(rootView, id);
      if (age1 == null) {
        break missingId;
      }

      id = R.id.email1;
      EditText email1 = ViewBindings.findChildViewById(rootView, id);
      if (email1 == null) {
        break missingId;
      }

      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      id = R.id.name1;
      EditText name1 = ViewBindings.findChildViewById(rootView, id);
      if (name1 == null) {
        break missingId;
      }

      id = R.id.pass1;
      EditText pass1 = ViewBindings.findChildViewById(rootView, id);
      if (pass1 == null) {
        break missingId;
      }

      id = R.id.signup;
      Button signup = ViewBindings.findChildViewById(rootView, id);
      if (signup == null) {
        break missingId;
      }

      id = R.id.textView4;
      TextView textView4 = ViewBindings.findChildViewById(rootView, id);
      if (textView4 == null) {
        break missingId;
      }

      id = R.id.textView5;
      TextView textView5 = ViewBindings.findChildViewById(rootView, id);
      if (textView5 == null) {
        break missingId;
      }

      return new ActivityMainBinding((ConstraintLayout) rootView, age1, email1, imageView2, name1,
          pass1, signup, textView4, textView5);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
