// Generated by view binder compiler. Do not edit!
package com.example.quiz.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.quiz.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentHomefragmentBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final ImageView coinwithdrawl;

  @NonNull
  public final TextView coinwithdrawl1;

  @NonNull
  public final LinearLayout linearLayout;

  @NonNull
  public final TextView name2;

  @NonNull
  public final ImageView profile;

  @NonNull
  public final RecyclerView recycleview;

  @NonNull
  public final TextView textView8;

  private FragmentHomefragmentBinding(@NonNull FrameLayout rootView,
      @NonNull ImageView coinwithdrawl, @NonNull TextView coinwithdrawl1,
      @NonNull LinearLayout linearLayout, @NonNull TextView name2, @NonNull ImageView profile,
      @NonNull RecyclerView recycleview, @NonNull TextView textView8) {
    this.rootView = rootView;
    this.coinwithdrawl = coinwithdrawl;
    this.coinwithdrawl1 = coinwithdrawl1;
    this.linearLayout = linearLayout;
    this.name2 = name2;
    this.profile = profile;
    this.recycleview = recycleview;
    this.textView8 = textView8;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentHomefragmentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentHomefragmentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_homefragment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentHomefragmentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.coinwithdrawl;
      ImageView coinwithdrawl = ViewBindings.findChildViewById(rootView, id);
      if (coinwithdrawl == null) {
        break missingId;
      }

      id = R.id.coinwithdrawl1;
      TextView coinwithdrawl1 = ViewBindings.findChildViewById(rootView, id);
      if (coinwithdrawl1 == null) {
        break missingId;
      }

      id = R.id.linearLayout;
      LinearLayout linearLayout = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout == null) {
        break missingId;
      }

      id = R.id.name2;
      TextView name2 = ViewBindings.findChildViewById(rootView, id);
      if (name2 == null) {
        break missingId;
      }

      id = R.id.profile;
      ImageView profile = ViewBindings.findChildViewById(rootView, id);
      if (profile == null) {
        break missingId;
      }

      id = R.id.recycleview;
      RecyclerView recycleview = ViewBindings.findChildViewById(rootView, id);
      if (recycleview == null) {
        break missingId;
      }

      id = R.id.textView8;
      TextView textView8 = ViewBindings.findChildViewById(rootView, id);
      if (textView8 == null) {
        break missingId;
      }

      return new FragmentHomefragmentBinding((FrameLayout) rootView, coinwithdrawl, coinwithdrawl1,
          linearLayout, name2, profile, recycleview, textView8);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
