// Generated by view binder compiler. Do not edit!
package com.example.quiz.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.quiz.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentProfilefragmentBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final TextView Country;

  @NonNull
  public final ConstraintLayout ExpandableconstraintLayout;

  @NonNull
  public final TextView age2;

  @NonNull
  public final TextView email2;

  @NonNull
  public final ImageView imageView7;

  @NonNull
  public final ImageView imagebutton;

  @NonNull
  public final LinearLayout linearLayout3;

  @NonNull
  public final LinearLayout linearLayout4;

  @NonNull
  public final LinearLayout linearLayout5;

  @NonNull
  public final LinearLayout linearLayout6;

  @NonNull
  public final TextView name2;

  @NonNull
  public final TextView nameUp;

  @NonNull
  public final TextView password2;

  @NonNull
  public final Button save;

  @NonNull
  public final TextView textView10;

  @NonNull
  public final TextView textView12;

  @NonNull
  public final TextView textView13;

  @NonNull
  public final TextView textView14;

  @NonNull
  public final TextView textView15;

  @NonNull
  public final TextView textView16;

  private FragmentProfilefragmentBinding(@NonNull FrameLayout rootView, @NonNull TextView Country,
      @NonNull ConstraintLayout ExpandableconstraintLayout, @NonNull TextView age2,
      @NonNull TextView email2, @NonNull ImageView imageView7, @NonNull ImageView imagebutton,
      @NonNull LinearLayout linearLayout3, @NonNull LinearLayout linearLayout4,
      @NonNull LinearLayout linearLayout5, @NonNull LinearLayout linearLayout6,
      @NonNull TextView name2, @NonNull TextView nameUp, @NonNull TextView password2,
      @NonNull Button save, @NonNull TextView textView10, @NonNull TextView textView12,
      @NonNull TextView textView13, @NonNull TextView textView14, @NonNull TextView textView15,
      @NonNull TextView textView16) {
    this.rootView = rootView;
    this.Country = Country;
    this.ExpandableconstraintLayout = ExpandableconstraintLayout;
    this.age2 = age2;
    this.email2 = email2;
    this.imageView7 = imageView7;
    this.imagebutton = imagebutton;
    this.linearLayout3 = linearLayout3;
    this.linearLayout4 = linearLayout4;
    this.linearLayout5 = linearLayout5;
    this.linearLayout6 = linearLayout6;
    this.name2 = name2;
    this.nameUp = nameUp;
    this.password2 = password2;
    this.save = save;
    this.textView10 = textView10;
    this.textView12 = textView12;
    this.textView13 = textView13;
    this.textView14 = textView14;
    this.textView15 = textView15;
    this.textView16 = textView16;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentProfilefragmentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentProfilefragmentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_profilefragment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentProfilefragmentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Country;
      TextView Country = ViewBindings.findChildViewById(rootView, id);
      if (Country == null) {
        break missingId;
      }

      id = R.id.ExpandableconstraintLayout;
      ConstraintLayout ExpandableconstraintLayout = ViewBindings.findChildViewById(rootView, id);
      if (ExpandableconstraintLayout == null) {
        break missingId;
      }

      id = R.id.age2;
      TextView age2 = ViewBindings.findChildViewById(rootView, id);
      if (age2 == null) {
        break missingId;
      }

      id = R.id.email2;
      TextView email2 = ViewBindings.findChildViewById(rootView, id);
      if (email2 == null) {
        break missingId;
      }

      id = R.id.imageView7;
      ImageView imageView7 = ViewBindings.findChildViewById(rootView, id);
      if (imageView7 == null) {
        break missingId;
      }

      id = R.id.imagebutton;
      ImageView imagebutton = ViewBindings.findChildViewById(rootView, id);
      if (imagebutton == null) {
        break missingId;
      }

      id = R.id.linearLayout3;
      LinearLayout linearLayout3 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout3 == null) {
        break missingId;
      }

      id = R.id.linearLayout4;
      LinearLayout linearLayout4 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout4 == null) {
        break missingId;
      }

      id = R.id.linearLayout5;
      LinearLayout linearLayout5 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout5 == null) {
        break missingId;
      }

      id = R.id.linearLayout6;
      LinearLayout linearLayout6 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout6 == null) {
        break missingId;
      }

      id = R.id.name2;
      TextView name2 = ViewBindings.findChildViewById(rootView, id);
      if (name2 == null) {
        break missingId;
      }

      id = R.id.name_up;
      TextView nameUp = ViewBindings.findChildViewById(rootView, id);
      if (nameUp == null) {
        break missingId;
      }

      id = R.id.password2;
      TextView password2 = ViewBindings.findChildViewById(rootView, id);
      if (password2 == null) {
        break missingId;
      }

      id = R.id.save;
      Button save = ViewBindings.findChildViewById(rootView, id);
      if (save == null) {
        break missingId;
      }

      id = R.id.textView10;
      TextView textView10 = ViewBindings.findChildViewById(rootView, id);
      if (textView10 == null) {
        break missingId;
      }

      id = R.id.textView12;
      TextView textView12 = ViewBindings.findChildViewById(rootView, id);
      if (textView12 == null) {
        break missingId;
      }

      id = R.id.textView13;
      TextView textView13 = ViewBindings.findChildViewById(rootView, id);
      if (textView13 == null) {
        break missingId;
      }

      id = R.id.textView14;
      TextView textView14 = ViewBindings.findChildViewById(rootView, id);
      if (textView14 == null) {
        break missingId;
      }

      id = R.id.textView15;
      TextView textView15 = ViewBindings.findChildViewById(rootView, id);
      if (textView15 == null) {
        break missingId;
      }

      id = R.id.textView16;
      TextView textView16 = ViewBindings.findChildViewById(rootView, id);
      if (textView16 == null) {
        break missingId;
      }

      return new FragmentProfilefragmentBinding((FrameLayout) rootView, Country,
          ExpandableconstraintLayout, age2, email2, imageView7, imagebutton, linearLayout3,
          linearLayout4, linearLayout5, linearLayout6, name2, nameUp, password2, save, textView10,
          textView12, textView13, textView14, textView15, textView16);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
