// Generated by view binder compiler. Do not edit!
package com.example.quiz.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.quiz.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentHistoryfragmentBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final TextView balance;

  @NonNull
  public final ImageView coinwithdrawl2;

  @NonNull
  public final RecyclerView historyrecyclerview;

  @NonNull
  public final LinearLayout linearLayout;

  @NonNull
  public final LinearLayout linearLayout2;

  @NonNull
  public final TextView name2;

  @NonNull
  public final ImageView profile;

  private FragmentHistoryfragmentBinding(@NonNull FrameLayout rootView, @NonNull TextView balance,
      @NonNull ImageView coinwithdrawl2, @NonNull RecyclerView historyrecyclerview,
      @NonNull LinearLayout linearLayout, @NonNull LinearLayout linearLayout2,
      @NonNull TextView name2, @NonNull ImageView profile) {
    this.rootView = rootView;
    this.balance = balance;
    this.coinwithdrawl2 = coinwithdrawl2;
    this.historyrecyclerview = historyrecyclerview;
    this.linearLayout = linearLayout;
    this.linearLayout2 = linearLayout2;
    this.name2 = name2;
    this.profile = profile;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentHistoryfragmentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentHistoryfragmentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_historyfragment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentHistoryfragmentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.balance;
      TextView balance = ViewBindings.findChildViewById(rootView, id);
      if (balance == null) {
        break missingId;
      }

      id = R.id.coinwithdrawl2;
      ImageView coinwithdrawl2 = ViewBindings.findChildViewById(rootView, id);
      if (coinwithdrawl2 == null) {
        break missingId;
      }

      id = R.id.historyrecyclerview;
      RecyclerView historyrecyclerview = ViewBindings.findChildViewById(rootView, id);
      if (historyrecyclerview == null) {
        break missingId;
      }

      id = R.id.linearLayout;
      LinearLayout linearLayout = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout == null) {
        break missingId;
      }

      id = R.id.linearLayout2;
      LinearLayout linearLayout2 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout2 == null) {
        break missingId;
      }

      id = R.id.name2;
      TextView name2 = ViewBindings.findChildViewById(rootView, id);
      if (name2 == null) {
        break missingId;
      }

      id = R.id.profile;
      ImageView profile = ViewBindings.findChildViewById(rootView, id);
      if (profile == null) {
        break missingId;
      }

      return new FragmentHistoryfragmentBinding((FrameLayout) rootView, balance, coinwithdrawl2,
          historyrecyclerview, linearLayout, linearLayout2, name2, profile);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
