// Generated by view binder compiler. Do not edit!
package com.example.quiz.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.quiz.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentSpinfragmentBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final Button Spin;

  @NonNull
  public final TextView balance2;

  @NonNull
  public final ImageView coinwithdrawl3;

  @NonNull
  public final ImageView imageView3;

  @NonNull
  public final LinearLayout linearLayout;

  @NonNull
  public final TextView name2;

  @NonNull
  public final ImageView profile;

  @NonNull
  public final TextView spinchance;

  @NonNull
  public final TextView textView7;

  @NonNull
  public final TextView textView9;

  @NonNull
  public final ImageView wheel;

  private FragmentSpinfragmentBinding(@NonNull FrameLayout rootView, @NonNull Button Spin,
      @NonNull TextView balance2, @NonNull ImageView coinwithdrawl3, @NonNull ImageView imageView3,
      @NonNull LinearLayout linearLayout, @NonNull TextView name2, @NonNull ImageView profile,
      @NonNull TextView spinchance, @NonNull TextView textView7, @NonNull TextView textView9,
      @NonNull ImageView wheel) {
    this.rootView = rootView;
    this.Spin = Spin;
    this.balance2 = balance2;
    this.coinwithdrawl3 = coinwithdrawl3;
    this.imageView3 = imageView3;
    this.linearLayout = linearLayout;
    this.name2 = name2;
    this.profile = profile;
    this.spinchance = spinchance;
    this.textView7 = textView7;
    this.textView9 = textView9;
    this.wheel = wheel;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentSpinfragmentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentSpinfragmentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_spinfragment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentSpinfragmentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Spin;
      Button Spin = ViewBindings.findChildViewById(rootView, id);
      if (Spin == null) {
        break missingId;
      }

      id = R.id.balance2;
      TextView balance2 = ViewBindings.findChildViewById(rootView, id);
      if (balance2 == null) {
        break missingId;
      }

      id = R.id.coinwithdrawl3;
      ImageView coinwithdrawl3 = ViewBindings.findChildViewById(rootView, id);
      if (coinwithdrawl3 == null) {
        break missingId;
      }

      id = R.id.imageView3;
      ImageView imageView3 = ViewBindings.findChildViewById(rootView, id);
      if (imageView3 == null) {
        break missingId;
      }

      id = R.id.linearLayout;
      LinearLayout linearLayout = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout == null) {
        break missingId;
      }

      id = R.id.name2;
      TextView name2 = ViewBindings.findChildViewById(rootView, id);
      if (name2 == null) {
        break missingId;
      }

      id = R.id.profile;
      ImageView profile = ViewBindings.findChildViewById(rootView, id);
      if (profile == null) {
        break missingId;
      }

      id = R.id.spinchance;
      TextView spinchance = ViewBindings.findChildViewById(rootView, id);
      if (spinchance == null) {
        break missingId;
      }

      id = R.id.textView7;
      TextView textView7 = ViewBindings.findChildViewById(rootView, id);
      if (textView7 == null) {
        break missingId;
      }

      id = R.id.textView9;
      TextView textView9 = ViewBindings.findChildViewById(rootView, id);
      if (textView9 == null) {
        break missingId;
      }

      id = R.id.wheel;
      ImageView wheel = ViewBindings.findChildViewById(rootView, id);
      if (wheel == null) {
        break missingId;
      }

      return new FragmentSpinfragmentBinding((FrameLayout) rootView, Spin, balance2, coinwithdrawl3,
          imageView3, linearLayout, name2, profile, spinchance, textView7, textView9, wheel);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
