// Generated by view binder compiler. Do not edit!
package com.example.quiz.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.quiz.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class HistoryitemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView coins;

  @NonNull
  public final ImageView imageView5;

  @NonNull
  public final TextView status;

  @NonNull
  public final TextView time;

  @NonNull
  public final LinearLayout timeanddate;

  private HistoryitemBinding(@NonNull ConstraintLayout rootView, @NonNull TextView coins,
      @NonNull ImageView imageView5, @NonNull TextView status, @NonNull TextView time,
      @NonNull LinearLayout timeanddate) {
    this.rootView = rootView;
    this.coins = coins;
    this.imageView5 = imageView5;
    this.status = status;
    this.time = time;
    this.timeanddate = timeanddate;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static HistoryitemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static HistoryitemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.historyitem, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static HistoryitemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.coins;
      TextView coins = ViewBindings.findChildViewById(rootView, id);
      if (coins == null) {
        break missingId;
      }

      id = R.id.imageView5;
      ImageView imageView5 = ViewBindings.findChildViewById(rootView, id);
      if (imageView5 == null) {
        break missingId;
      }

      id = R.id.status;
      TextView status = ViewBindings.findChildViewById(rootView, id);
      if (status == null) {
        break missingId;
      }

      id = R.id.time;
      TextView time = ViewBindings.findChildViewById(rootView, id);
      if (time == null) {
        break missingId;
      }

      id = R.id.timeanddate;
      LinearLayout timeanddate = ViewBindings.findChildViewById(rootView, id);
      if (timeanddate == null) {
        break missingId;
      }

      return new HistoryitemBinding((ConstraintLayout) rootView, coins, imageView5, status, time,
          timeanddate);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
